name: Přesměrování PR do nové větve

on:
  pull_request_target:
    branches: [ main ]

jobs:
  presmerovat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kód
        uses: actions/checkout@v3

      - name: Získání informací o PR
        id: pr
        run: |
          echo "::set-output name=number::${{ github.event.pull_request.number }}"
          echo "::set-output name=head_ref::${{ github.event.pull_request.head.ref }}"
          echo "::set-output name=head_repo::${{ github.event.pull_request.head.repo.full_name}}"

      - name: Vytvoření nové větve
        run: |
          gh pr checkout ${{ steps.pr.outputs.number }}
          git checkout -b "${{ github.event.pull_request.user.login }}"
          git push origin "${{ github.event.pull_request.user.login }}"

      - name: Aktualizace cílové větve PR
        run: |
          gh pr edit ${{ steps.pr.outputs.number }} --base "pr-${{ steps.pr.outputs.number }}-auto"

      - name: Přidání komentáře k PR
        run: |
          gh pr comment ${{ steps.pr.outputs.number }} --body "Pull request byl automaticky přesměrován do větve pr-${{ steps.pr.outputs.number }}-auto."
